name: Compile and test the plugin
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build the artifacts with maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Build using maven
        run: mvn clean package
      - uses: actions/upload-artifact@v2
        with:
          path: target/Challenge-*.jar
          name: plugin_jar
  test:
    name: Test the plugin using a actual minecraft server
    runs-on: ubuntu-latest
    environment: mc_server
    needs: [build]
    steps:
      - name: Download the plugin jar
        uses: actions/download-artifact@v2
        with:
          name: plugin_jar
      - name: will be removed later
        run: ls