name: Compile and test the plugin
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build the artifacts with maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build using maven
        run: mvn clean package
      - uses: actions/upload-artifact@v2
        with:
          path: target/Challenge-*.jar
          name: plugin_jar
  test:
    name: Test the plugin using a actual minecraft server
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download the plugin jar
        uses: actions/download-artifact@v2
        with:
          name: plugin_jar
      - name: Download java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"
      - name: Download PaperMC
        uses: just-dev-creator/install-paper@v1.0.1
        with:
          path: ./paperclip.jar
      - name: Create JUtils configuration direcotry
        run: mkdir -p plugins/JUtils
      - name: Put license key
        run: "echo LICENSE-KEY: ${{ secrets.PLUGIN_LICENSE_KEY }} > plugins/JUtils/license.yml"
      - name: Agree to EULA
        run: "echo eula=true > eula.txt"
      - name: Move plugin to folder
        run: "mv ./Challenge-*.jar ./plugins"
      - name: Enable testing mode
        run: touch isGitHub
      - name: Start server
        timeout-minutes: 2
        run: "java -jar paperclip.jar"
